#include QMK_KEYBOARD_H
#include "keymap_common.h"

#ifdef RGB_MATRIX_ENABLE

#define HSV_NULL {HSV_OFF}
#define HSV_BASE {HSV_WHITE}
#define HSV_QWERTY {HSV_RED}
#define HSV_WINDOWS {HSV_SPRINGGREEN}
#define HSV_BUTTON {HSV_PINK}
#define HSV_NAV {HSV_CYAN}
#define HSV_MOUSE {HSV_YELLOW}
#define HSV_MEDIA {HSV_PURPLE}
#define HSV_NUM {HSV_BLUE}
#define HSV_NUMPAD {HSV_TURQUOISE}
#define HSV_SYM {HSV_GREEN}
#define HSV_FUN {HSV_ORANGE}
#define HSV_INVERTED_T {HSV_MAGENTA}
#define HSV_BOOT {HSV_RED}

#define LEDS(L00, L01, L02, L03, L04, L05, R00, R01, R02, R03, R04, R05, \
             L06, L07, L08, L09, L10, L11, R06, R07, R08, R09, R10, R11, \
             L12, L13, L14, L15, L16, L17, R12, R13, R14, R15, R16, R17, \
                            L18, L19, L20, R18, R19, R20, \
             UL0, UL1, UL2, UL3, UL4, UL5, UR0, UR1, UR2, UR3, UR4, UR5 \
            ) { \
                UL0, UL1, UL2, UL3, UL4, UL5, \
                L20, L17, L11, L05, \
                L04, L10, L16, L19, \
                L18, L15, L09, L03, \
                L02, L08, L14, \
                L13, L07, L01, \
                L00, L06, L12, \
                UR0, UR1, UR2, UR3, UR4, UR5, \
                R18, R12, R06, R00, \
                R01, R07, R13, R19, \
                R20, R14, R08, R02, \
                R03, R09, R15, \
                R16, R10, R04, \
                R05, R11, R17 \
            }

hsv_t layer_colors_hsv[11][54] = {
    [_BASE] = LEDS(
        HSV_NULL, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE,  HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_NULL,
        HSV_NULL, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE,  HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_NULL,
        HSV_NULL, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE,  HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_NULL,
                                       HSV_FUN, HSV_NUM,  HSV_SYM,  HSV_MOUSE, HSV_NAV,  HSV_MEDIA,
        HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE,  HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE, HSV_BASE
    ),
    [_EXTRA] = LEDS(
        HSV_NULL,   HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_NULL,
        HSV_NULL,   HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_NULL,
        HSV_NULL,   HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_NULL,
                                            HSV_FUN,    HSV_NUM,    HSV_SYM,    HSV_MOUSE,  HSV_NAV,    HSV_MEDIA,
        HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY, HSV_QWERTY
    ),
    [_TAP] = LEDS(
        HSV_NULL,    HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_NULL,
        HSV_NULL,    HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_NULL,
        HSV_NULL,    HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_NULL,
                                               HSV_FUN,     HSV_NUM,     HSV_SYM,     HSV_MOUSE,   HSV_NAV,     HSV_MEDIA,
        HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS, HSV_WINDOWS
    ),
    [_BUTTON] = LEDS(
        HSV_NULL,   HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_NULL,
        HSV_NULL,   HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_NULL,
        HSV_NULL,   HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_NULL,
                                            HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON,
        HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON, HSV_BUTTON
    ),
    [_NAV] = LEDS(
        HSV_NULL, HSV_NAV, HSV_NAV,        HSV_INVERTED_T, HSV_NAV,        HSV_NAV, HSV_NULL, HSV_BASE, HSV_QWERTY, HSV_WINDOWS, HSV_BOOT, HSV_NULL,
        HSV_NULL, HSV_NAV, HSV_INVERTED_T, HSV_INVERTED_T, HSV_INVERTED_T, HSV_NAV, HSV_NAV,  HSV_NAV,  HSV_NAV,    HSV_NAV,     HSV_NAV,  HSV_NULL,
        HSV_NULL, HSV_NAV, HSV_NAV,        HSV_NAV,        HSV_NAV,        HSV_NAV, HSV_NULL, HSV_NAV,  HSV_NUM,    HSV_NULL,    HSV_NULL, HSV_NULL,
                                           HSV_NAV,        HSV_NAV,        HSV_NAV, HSV_NULL, HSV_NULL, HSV_NULL,
        HSV_NAV,  HSV_NAV, HSV_NAV,        HSV_NAV,        HSV_NAV,        HSV_NAV, HSV_NAV,  HSV_NAV,  HSV_NAV,    HSV_NAV,     HSV_NAV,  HSV_NULL
    ),
    [_MOUSE] = LEDS(
        HSV_NULL,  HSV_MOUSE, HSV_MOUSE,      HSV_INVERTED_T, HSV_MOUSE,      HSV_MOUSE, HSV_NULL,  HSV_BASE,  HSV_QWERTY, HSV_WINDOWS, HSV_BOOT,  HSV_NULL,
        HSV_NULL,  HSV_MOUSE, HSV_INVERTED_T, HSV_INVERTED_T, HSV_INVERTED_T, HSV_MOUSE, HSV_MOUSE, HSV_MOUSE, HSV_MOUSE,  HSV_MOUSE,   HSV_MOUSE, HSV_NULL,
        HSV_NULL,  HSV_MOUSE, HSV_MOUSE,      HSV_MOUSE,      HSV_MOUSE,      HSV_MOUSE, HSV_NULL,  HSV_MOUSE, HSV_SYM,    HSV_NULL,    HSV_NULL,  HSV_NULL,
                                              HSV_MOUSE,      HSV_MOUSE,      HSV_MOUSE, HSV_NULL,  HSV_NULL,  HSV_NULL,
        HSV_MOUSE, HSV_MOUSE, HSV_MOUSE,      HSV_MOUSE,      HSV_MOUSE,      HSV_MOUSE, HSV_MOUSE, HSV_MOUSE, HSV_MOUSE,  HSV_MOUSE,   HSV_MOUSE, HSV_MOUSE
    ),
    [_MEDIA] = LEDS(
        HSV_NULL,  HSV_MEDIA, HSV_MEDIA,      HSV_INVERTED_T, HSV_MEDIA,      HSV_MEDIA, HSV_NULL,  HSV_BASE,  HSV_QWERTY, HSV_WINDOWS, HSV_BOOT,  HSV_NULL,
        HSV_NULL,  HSV_MEDIA, HSV_INVERTED_T, HSV_INVERTED_T, HSV_INVERTED_T, HSV_MEDIA, HSV_MEDIA, HSV_MEDIA, HSV_MEDIA,  HSV_MEDIA,   HSV_MEDIA, HSV_NULL,
        HSV_NULL,  HSV_MEDIA, HSV_MEDIA,      HSV_MEDIA,      HSV_MEDIA,      HSV_MEDIA, HSV_NULL,  HSV_MEDIA, HSV_FUN,    HSV_NULL,    HSV_NULL,  HSV_NULL,
                                              HSV_MEDIA,      HSV_MEDIA,      HSV_MEDIA, HSV_NULL,  HSV_NULL,  HSV_NULL,
        HSV_MEDIA, HSV_MEDIA, HSV_MEDIA,      HSV_MEDIA,      HSV_MEDIA,      HSV_MEDIA, HSV_MEDIA, HSV_MEDIA, HSV_MEDIA,  HSV_MEDIA,   HSV_MEDIA, HSV_MEDIA
    ),
    [_NUM] = LEDS(
        HSV_NULL, HSV_BOOT, HSV_WINDOWS, HSV_QWERTY, HSV_BASE, HSV_NULL, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NULL,
        HSV_NULL, HSV_NUM,  HSV_NUM,     HSV_NUM,    HSV_NUM,  HSV_NUM,  HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NULL,
        HSV_NULL, HSV_NULL, HSV_NULL,    HSV_NAV,    HSV_NUM,  HSV_NULL, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NULL,
                                         HSV_NULL,   HSV_NULL, HSV_NULL, HSV_NUM, HSV_NUM, HSV_NUM,
        HSV_NUM,  HSV_NUM,  HSV_NUM,     HSV_NUM,    HSV_NUM,  HSV_NUM,  HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM, HSV_NUM
    ),
    [_NUMPAD] = LEDS(
        HSV_NULL,   HSV_BOOT,   HSV_WINDOWS, HSV_QWERTY, HSV_BASE,   HSV_NULL,   HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NULL,
        HSV_NULL,   HSV_NUMPAD, HSV_NUMPAD,  HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NULL,
        HSV_NULL,   HSV_NULL,   HSV_NULL,    HSV_NAV,    HSV_NUMPAD, HSV_NULL,   HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NULL,
                                             HSV_NULL,   HSV_NULL,   HSV_NULL,   HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD,
        HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD,  HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD, HSV_NUMPAD
    ),
    [_SYM] = LEDS(
        HSV_NULL, HSV_BOOT, HSV_WINDOWS, HSV_QWERTY, HSV_BASE,  HSV_NULL, HSV_SYM,  HSV_SYM,  HSV_SYM, HSV_SYM, HSV_SYM, HSV_NULL,
        HSV_NULL, HSV_SYM,  HSV_SYM,     HSV_SYM,    HSV_SYM,   HSV_SYM,  HSV_SYM,  HSV_SYM,  HSV_SYM, HSV_SYM, HSV_SYM, HSV_NULL,
        HSV_NULL, HSV_NULL, HSV_NULL,    HSV_MOUSE,  HSV_SYM,   HSV_NULL, HSV_SYM,  HSV_SYM,  HSV_SYM, HSV_SYM, HSV_SYM, HSV_NULL,
                                         HSV_NULL,   HSV_NULL,  HSV_NULL, HSV_SYM,  HSV_SYM,  HSV_SYM,
        HSV_SYM,  HSV_SYM,  HSV_SYM,     HSV_SYM,    HSV_SYM,   HSV_SYM,  HSV_SYM,  HSV_SYM,  HSV_SYM, HSV_SYM, HSV_SYM, HSV_SYM
    ),
    [_FUN] = LEDS(
        HSV_NULL, HSV_BOOT, HSV_WINDOWS, HSV_QWERTY, HSV_BASE,  HSV_NULL, HSV_FUN,  HSV_FUN,  HSV_FUN, HSV_FUN, HSV_FUN, HSV_NULL,
        HSV_NULL, HSV_FUN,  HSV_FUN,     HSV_FUN,    HSV_FUN,   HSV_FUN,  HSV_FUN,  HSV_FUN,  HSV_FUN, HSV_FUN, HSV_FUN, HSV_NULL,
        HSV_NULL, HSV_NULL, HSV_NULL,    HSV_MEDIA,  HSV_FUN,   HSV_NULL, HSV_FUN,  HSV_FUN,  HSV_FUN, HSV_FUN, HSV_FUN, HSV_NULL,
                                         HSV_NULL,   HSV_NULL,  HSV_NULL, HSV_FUN,  HSV_FUN,  HSV_FUN,
        HSV_FUN,  HSV_FUN,  HSV_FUN,     HSV_FUN,    HSV_FUN,   HSV_FUN,  HSV_FUN,  HSV_FUN,  HSV_FUN, HSV_FUN, HSV_FUN, HSV_FUN
    )
};

bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    uint8_t layer = get_highest_layer(layer_state | default_layer_state);

    for (uint8_t i = led_min; i < led_max; i++) {
        hsv_t hsv = layer_colors_hsv[layer][i];
        if (hsv.v > rgb_matrix_get_val()) {
            hsv.v = rgb_matrix_get_val();
        }
        rgb_t rgb = hsv_to_rgb(hsv);
        rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
    }
    return false;
}

#endif // RGB_MATRIX_ENABLE
